name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies: # Ini adalah SATU-SATUNYA blok 'dependencies:' yang harus ada
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2  # Pindahkan ini ke bawah 'flutter: sdk: flutter'
  http: ^1.2.1             # Pindahkan ini ke bawah 'flutter: sdk: flutter'
  flutter_riverpod: ^2.5.1 # Pindahkan ini ke bawah 'flutter: sdk: flutter'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true